// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	Comments string
	Likes    string
	Posts    string
	Users    string
}{
	Comments: "comments",
	Likes:    "likes",
	Posts:    "posts",
	Users:    "users",
}
